apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-hpa
  namespace: {{ .Values.app.namespace }}
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}-deployment
  targetCPUUtilizationPercentage: 20