apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.app.namespace }}
  name: service-{{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
  - name: {{ .Values.service.portName }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  type: LoadBalancer