replicaCount: 1
app:
  namespace: model-serving
  env: dev
image:
  repository: edlongbottom/mlwebservice-titanic 
  tag: 0.0.1
  pullPolicy: IfNotPresent
service:
  portName: flask-api
  port: 5000
  containerPort: 5000 