# workflow to build and test model as containerised prediction service
name: titanic-mlwebservice-test

# when should a docker image build be triggered?
on:
  push:
    paths:
      - 'deployment/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: deployment/

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.6'
      - 
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install json requests
      -
        name: Run prediction service
        run: |
          python api.py
      -
        name: Test web service using Requests
        run: |
          cd tests/
          python request-test.py